apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alltrails
spec:
  secretName: nginx-tls
  duration: 720h
  renewBefore: 96h
  subject:
    organizations:
    - alltrails
  dnsNames:
  - kubernetes.docker.internal
  issuerRef:
    name: dummy-ca
