apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nav
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nav
  targetCPUUtilizationPercentage: 10
